services:
  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backoffice/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
